### ISSUE TITLE
Poss bug in GET /decks/first/:deck_id

### ISSUE THREAD

**Issue by Roger-Heathcote** [fac19/Cardley---backend#30]
Tom reports only getting this back from his fetch request... Investigate

webpackHotDevClient.js:138 ./src/components/pages/Practice/practice.js
  Line 40:20:  'setCardColor' is assigned a value but never used                                                                        no-unused-vars
  Line 44:22:  'setCorrectCard' is assigned a value but never used                                                                      no-unused-vars
  Line 59:5:   React Hook useEffect has a missing dependency: 'props.deckToPractice'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
practice.js:57 WE GOT THIS BACK: {current_position: 0}

{"current_position":0}

**Comment by Roger-Heathcote** [comment]
Hi Tom, I tested this route in postman and it looks fine...

I logged in as admin by POSTing to: https://cardley-api.herokuapp.com/login
With the raw JSON body of...
{
	"email": "admin@iscool.com",
	"password": "password"
}

I then used that API token to do a GET to
https://cardley-api.herokuapp.com/decks/first/1

And I got...
{
    "current_position": 0,
    "deck_length": 4,
    "card": {
        "card_id": 2,
        "deck_id": 1,
        "front_text": "bed",
        "front_image": "http://t0.gstatic.com/images?q=tbn:ANd9GcSuAm_C-ktaK_ZxXxZlMSqE_JvM1QULef5F91fK1QFOF2SGVeTVLP2x9VTmvFn493RkXQdJokbt5sp0MzvaEWk",
        "back_text": "lit",
        "back_image": null,
        "important": true,
        "color": "rgb(174,232,143)"
    }
}

I then logged in as tom@iscool.com and asked for the first card of deck 1 and got the {"current_position":0} that you mentioned. This IS a bug but it's not that you should be getting a card back. tom@iscool.com is not the owner of deck 1, that's a private deck belonging to admin@iscool.com. What you should be getting back for that is an error that tells you you are unauthorised.

I noticed we weren't checking the deck owners properly earlier today and have logged a bug that I hope to fix soon. https://github.com/fac19/Cardley---backend/issues/32 

In the meantime you can get deck which are part of the users collection fine. admin@iscool.com has decks 1 & 2 in their collection, tom@iscool.com has decks 2 & 3. Note deck three has no cards in it though!

**Comment by tacotoemeck** [comment]
Great, that makes sense! Thanks so much for looking into this.
